image: fermiumlabs/latex-docker:latest

pipelines:
  custom: # Manually only
    build_full:
      - step:
          script:
            - pdflatex prezentacja.tex && bibtex prezentacja && pdflatex prezentacja.tex && pdflatex prezentacja.tex
    build_fast:
      - step:
          script:
            - pdflatex prezentacja.tex