image: sharelatex/sharelatex

clone:
  lfs: true

pipelines:
  custom: # Manually only
    build_full:
      - step:
          caches:
            - sharelatex
          script:
            - pdflatex latex/prezentacja.tex && bibtex latex/prezentacja && pdflatex latex/prezentacja.tex && pdflatex latex/prezentacja.tex
    build_fast:
      - step:
          caches:
            - sharelatex
          script:
            - latex latex/prezentacja.tex

definitions:
  caches:
    sharelatex: sharelatex/sharelatex