image: blang/latex:ctanfull

clone:
  lfs: true

pipelines:
  custom: # Manually only
    build_full:
      - step:
          caches:
            - latex
          script:
            - pdflatex latex/prezentacja.tex && bibtex latex/prezentacja && pdflatex latex/prezentacja.tex && pdflatex latex/prezentacja.tex
    build_fast:
      - step:
          caches:
            - latex
          script:
            - pdflatex latex/prezentacja.tex

definitions:
  caches:
    latex: blang/latex